### ISSUE TITLE
Tools to convert to bs2

### ISSUE THREAD

**Issue by Jbwasse2** [bamsumit/slayerPytorch#10]
What tools did you use to convert the DVS128 Gesture Dataset to bs2?

**Comment by bamsumit** [comment]
Hi,
You can read the aedat files using tools from inviation: https://gitlab.com/inivation/dv-python and save them to bs2 or npy format to use during training. Something like this should work. This is not tested though.

```
import numpy as np
import matplotlib.pyplot as plt
import slayerSNN as snn
from dv import LegacyAedatFile

path = 'path_to_aedat_files'

actionName = [
    'hand_clapping',
    'right_hand_wave',
    'left_hand_wave',
    'right_arm_clockwise',
    'right_arm_counter_clockwise',
    'left_arm_clockwise', 
    'left_arm_counter_clockwise',
    'arm_roll',
    'air_drums',
    'air_guitar',
    'other_gestures',
]

def readAedatEvent(filename):
    xEvent = []
    yEvent = []
    pEvent = []
    tEvent = []
    with LegacyAedatFile(filename) as f:
        for event in f:
            xEvent.append(event.x)
            yEvent.append(event.y)
            pEvent.append(event.polarity)
            tEvent.append(event.timestamp/1000)

    return xEvent, yEvent, pEvent, tEvent

def splitData(filename, path):
    x, y, p, t = scipy.io.loadmat(path + filename + '.aedat')
    labels = np.loadtxt(path + filename + '_labels.csv', delimiter=',', skiprows=1)
    labels[:,0]  -= 1
    labels[:,1:]

    if not os.path.isdir('data/' + filename):
        os.mkdir('data/' + filename)

    lastAction = 100
    for action, tst, ten in labels:
        if action == lastAction:    continue # This is to ignore second arm_roll samples
        print(actionName[int(action)])
        ind = (t >= tst) & (t < ten)
        TD = snn.io.event(x[ind], y[ind], p[ind], (t[ind] - tst)/1000)
        # snn.io.showTD(TD)
        lastAction = action

        snn.io.encodeNpSpikes('data/'+ filename + '/{:g}.npy'.format(action), TD)

if __name__ == '__main__':
    user = np.arange(29) + 1
    lighting = [
        'fluorescent',
        'fluorescent_led',
        'lab',
        'led',
        'natural',
    ]

    count = 0
    for id in user:
        for light in lighting:
            filename = 'user{:02d}_{}'.format(id, light)

            if os.path.isfile(path + filename + '.aedat'):
                print(count, filename)
                splitData(filename, path)
                count += 1
```

**Comment by tasbolat1** [comment]
Hello @bamsumit,
You have mentioned that you've used 30 as false postive and 180 as true positive for DVS gesture dataset. However, I can't find the info on how you binned the data. How the DVS gesture dataset was loaded to the model? is there any binning?

**Comment by giacomop96** [comment]
Hi, I was trying to preprocessing the DVS Gesture dataset, but I get this error. The path is right since I have tried to read the data with the readAedatevent function and everything works well. 
Any suggestions?

0 user01_fluorescent
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-48-e8eb161a5656> in <module>()
     23                 #for i in range(20):
     24                 #  print(x[i], y[i], p[i],t[i])
---> 25                 splitData(filename, path)
     26                 count += 1

3 frames
<ipython-input-36-eba706fdc6eb> in splitData(filename, path)
      1 def splitData(filename, path):
----> 2     x, y, p, t = scipy.io.loadmat(path + filename + '.aedat')
      3     print(x,y,p,t)
      4     labels = np.loadtxt(path + filename + '_labels.csv', delimiter=',', skiprows=1)
      5     labels[:,0]  -= 1

/usr/local/lib/python3.6/dist-packages/scipy/io/matlab/mio.py in loadmat(file_name, mdict, appendmat, **kwargs)
    215     variable_names = kwargs.pop('variable_names', None)
    216     with _open_file_context(file_name, appendmat) as f:
--> 217         MR, _ = mat_reader_factory(f, **kwargs)
    218         matfile_dict = MR.get_variables(variable_names)
    219 

/usr/local/lib/python3.6/dist-packages/scipy/io/matlab/mio.py in mat_reader_factory(file_name, appendmat, **kwargs)
     70     """
     71     byte_stream, file_opened = _open_file(file_name, appendmat)
---> 72     mjv, mnv = get_matfile_version(byte_stream)
     73     if mjv == 0:
     74         return MatFile4Reader(byte_stream, **kwargs), file_opened

/usr/local/lib/python3.6/dist-packages/scipy/io/matlab/miobase.py in get_matfile_version(fileobj)
    239     if maj_val in (1, 2):
    240         return ret
--> 241     raise ValueError('Unknown mat file type, version %s, %s' % ret)
    242 
    243 

ValueError: Unknown mat file type, version 0, 154
