### ISSUE TITLE
The weight dimension does not match the input dimension

### ISSUE THREAD

**Issue by manwu1994** [bamsumit/slayerPytorch#53]
Hi, I try to implement the NMNIST with my model based on pytorch and source python code of N_MNIST, not slayerlayer, for example:
```
self.conv1 = nn.Sequential(
            nn.Conv2d(2, 16, 5, 1, 1),
            nn.BatchNorm2d(16))
        self.conv2 = nn.Sequential(
            nn.Conv2d(16, 16, 5),
            nn.BatchNorm2d(16))
        self.conv3 = nn.Sequential(
            nn.Conv2d(16, 16, 5),
            nn.BatchNorm2d(16))
```
But the input dimension is [8, 2, 34, 34, 300] , could you give me any suggestion to resolve it?
Thank you so much for your time.

**Comment by bamsumit** [comment]
I am not sure what you are trying to do. I am assuming you are using the dataloader in SLAYER example. 

Since NMNIST is a event-based video, not a static image, there a is time dimension associated with it which is the fifth dimension, 300 you get as the data is 300ms long. It is expected. If you want to use Conv2d process on top of it, then you have to get rid of the time dimension. Some ways to do it is by slicing in time to 300 points, or sum along time dimension.

**Comment by manwu1994** [comment]
Thank you for your kind reply. Could you talk about how to slicing the dataset to 300 points? Thank you again for all.

**Comment by bamsumit** [comment]
Just take `spikes[:,:,:,:,10]` to take the 11th slice and so on.
