### ISSUE TITLE
Why do you set the width and height both to 34, shouldn`t that be 28?

### ISSUE THREAD

**Issue by zhangxiann** [bamsumit/slayerPytorch#57]
Hi, I`m confused abount the width and height that you use in the code at line 30: [https://github.com/bamsumit/slayerPytorch/blob/master/example/02_NMNIST_MLP/nmnistMLP.py](https://github.com/bamsumit/slayerPytorch/blob/master/example/02_NMNIST_MLP/nmnistMLP.py)
```
inputSpikes = snn.io.read2Dspikes(
                self.path + str(inputIndex.item()) + '.bs2'
                ).toSpikeTensor(torch.zeros((2,34,34,self.nTimeBins)),
                samplingTime=self.samplingTime)
desiredClass = torch.zeros((10, 1, 1, 1))
```
The width and height are both **34**.
But according to the paper the the [docs](https://www.garrickorchard.com/datasets/n-mnist),  the width and height should both be **28**.
![image](https://user-images.githubusercontent.com/12131262/113401521-0b7da480-93d6-11eb-8004-551f9fa2d565.png)
Why the width and height has changed?

**Comment by bamsumit** [comment]
The MNIST image is moved in an saccadic motion to create N-MNIST. As a result, the dimension increase to 34x34. Since the saccadic motion is repeatable, you can compensate for the movement to get the motion compensated version of N-MNIST which is 28x28. We want the network to learn to compensate for the saccadic motion, so full 34x34 resolution is used.
