### ISSUE TITLE
Version problem of Matplotlib in requirements.txt

### ISSUE THREAD

**Issue by lgdlkq** [bamsumit/slayerPytorch#63]
Hello, I am just starting to learn about this.
When I finished configuring the environment and executed the command "python -m unittest" in the test directory, I got the error "ImportError: Failed to import any qt binding ".I solved this problem by updating the matplotlib version to 3.4.2.
My system and environment configuration：
OS：ubuntu18.04 LTS
python：3.8.5
gcc：7.5.0
cuda：11.1
I hope the author can check this problem and fix the file, thanks！

**Comment by morgsmss7** [comment]
I'm not the author, but installing the latest matplotlib version and using the requirements.txt for the rest seems to be working for me so far...

**Comment by bamsumit** [comment]
Thanks for the info. The issue might have come up with new version of the library. For now, you should be able to install the latest version of the (any) library and have it working. I'll check and fix it when I have a chance.

**Comment by forestfangsenlin** [comment]
The latest matplotlib version is working for me, however, when I use the snn.io.showTD function to show the spike images, it failed and only shows black images. I fixed it by degraded the matplotlib to 3.1.3 version.

**Comment by bamsumit** [comment]
@forestfangsenlin I recently tested with `matplotlib 3.4.1` (`Ubuntu 20.04`, `python 3.8.8` and `python 3.8.10`) and it seems to be working fine for me.

The black image might be due to network latency in rendering the plot (if you are running it from a network server). You could try adding an argument `repeat=True` in `showTD` and it will loop the animation.

Anyway as long as you have it working, it's fine.
